#pragma once

#define OLED_SDA_PIN GPIO_NUM_4
#define OLED_SCL_PIN GPIO_NUM_15
#define OLED_RST_PIN GPIO_NUM_16

#define LORA_MISO_PIN GPIO_NUM_19
#define LORA_MOSI_PIN GPIO_NUM_27
#define LORA_SCK_PIN GPIO_NUM_5
#define LORA_CS_PIN GPIO_NUM_18
#define LORA_RST_PIN GPIO_NUM_14
