#pragma once

#define MAG_DECLINATION_ANGLE -20.45

#define GPS_UART_RX_PIN 40
#define GPS_UART_TX_PIN 39

#define LORA_TX_PIN GPIO_NUM_17
#define LORA_RX_PIN GPIO_NUM_16
#define LORA_AUX_PIN GPIO_NUM_5
#define LORA_M0_PIN GPIO_NUM_18
#define LORA_M1_PIN GPIO_NUM_19

#define LORA_UART_BAUD_RATE 9600
#define LORA_CHANNEL 23
